version: 0.2

env:
  variables:
    ACCOUNT_ID:      "988732899429"
    REGION:          "us-east-1"
    IMAGE_REPO_NAME: "miso_fargate"

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Instalando dependencias del proyecto..."
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "Ejecutando pruebas unitarias con pytest..."
      - pytest tests/
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 988732899429.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo "build started on `date`"
      - echo "Building the Docker image..."
      - docker build -t miso_fargate .
      - docker tag miso_fargate:latest 988732899429.dkr.ecr.us-east-1.amazonaws.com/miso_fargate:latest

  post_build:
    commands:
      - echo "Build completed on `date`"
      - echo "Pushing the Docker image..."
      - docker push 988732899429.dkr.ecr.us-east-1.amazonaws.com/miso_fargate:latest
      - echo "writing image definitions file..."
      - printf '[{"name":"miso_fargate","imageUri":"%s"}]' 988732899429.dkr.ecr.us-east-1.amazonaws.com/miso_fargate:latest > imagedefinitions.json
      - printf '{"imageURI":"%s"}' 988732899429.dkr.ecr.us-east-1.amazonaws.com/miso_fargate:latest > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files:
    - '**/*'
    - imagedefinitions.json
    - imagedetails.json
  secondary-artifacts:
    definitionsartifact:
      files:
        - appspec.json
        - taskdef.json
      discard-paths: yes
    imageartifact:
      files:
        - imagedetails.json
