version: 0.2

env:
  variables:
    # Parámetros de tu ECR
    ECR_REGISTRY: 988732899429.dkr.ecr.us-east-1.amazonaws.com
    ECR_REPOSITORY: miso_fargate
    IMAGE_TAG: latest

phases:
  pre_build:
    commands:
      - echo "🔐 Authenticate Docker to Amazon ECR..."
      - aws ecr get-login-password --region us-east-1 \
        | docker login --username AWS --password-stdin $ECR_REGISTRY

  build:
    commands:
      - echo "🐳 Building the Docker image..."
      - docker build -t $ECR_REPOSITORY .
      - docker tag $ECR_REPOSITORY:latest $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

  post_build:
    commands:
      - echo "🚀 Pushing the image to ECR..."
      - docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      # 1) imagedefinitions.json para CodeDeploy/ECS (usado en la etapa de deploy)
      - printf '[{"name":"%s","imageUri":"%s"}]' \
          $ECR_REPOSITORY $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
        > imagedefinitions.json

      # 2) imageDetail.json (si tu pipeline lo requiere, p.ej. para notificaciones)
      - printf '{"imageUri":"%s"}' \
          $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
        > imageDetail.json

artifacts:
  files:
    - imagedefinitions.json
    - imageDetail.json
    - appspec.json
    - taskdef.json
