version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 988732899429.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo "Build started on `date`"
      - echo "Building the Docker image..."
      - docker build -t miso_fargate .
      - docker tag miso_fargate:latest 988732899429.dkr.ecr.us-east-1.amazonaws.com/miso_fargate:latest

  post_build:
    commands:
      - echo "Build completed on `date`"
      - echo "Pushing the Docker image..."
      - docker push 988732899429.dkr.ecr.us-east-1.amazonaws.com/miso_fargate:latest
      - echo "Writing image definitions file..."
      - printf '[{"name":"Container-app-python-miso","imageUri":"%s"}]' 988732899429.dkr.ecr.us-east-1.amazonaws.com/miso_fargate:latest > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files:
    - '**/*'
    - imagedefinitions.json  
  secondary-artifacts:
    definitionsartifact:
      files:
        - appspec.json
        - taskdef.json
      discard-paths: yes
    imageartifact:
      files:
        - imagedefinitions.json
    BuildArtifact:
        files:
          - '**/*'
          