version: 0.2

env:
  variables:
    ECR_REGISTRY: 988732899429.dkr.ecr.us-east-1.amazonaws.com
    ECR_REPOSITORY: miso_fargate
    IMAGE_TAG: latest

phases:
  pre_build:
    commands:
      - echo "🔐 Authenticate Docker to Amazon ECR (CLI v1)..."
      - $(aws ecr get-login --no-include-email --region us-east-1)

  build:
    commands:
      - echo "🐳 Building the Docker image..."
      - docker build -t $ECR_REPOSITORY .
      - docker tag $ECR_REPOSITORY:latest $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

  post_build:
    commands:
      - echo "🚀 Pushing the image to ECR..."
      - docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - printf '[{"name":"%s","imageUri":"%s"}]' \
          $ECR_REPOSITORY $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
        > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
    - appspec.json
    - taskdef.json
